name: Build and Push CP03 API

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositorio
        uses: actions/checkout@v4

      - name: Login no Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: acrcp03popovici.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build e Push da imagem
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: acrcp03popovici.azurecr.io/cp03-api:latest